### ISSUE TITLE
Use to different image when duplicate build

### ISSUE THREAD

**Issue by autumo** [zaiminc/gocat#17]
I use combine deploy. 
If the image is updated by a build that ran concurrently while deploying the `my-repo-web`, the `my-repo-server` image is different.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-repo
  labels:
    gocat.zaim.net/configmap-type: project
data:
  Kind: combine
  DockerRegistry: xxxx.dkr.ecr.ap-northeast-1.amazonaws.com/my-repo
  Alias: ^(oyako)$
  GitHubRepository: my-repo
  Steps: |
    - my-repo-web
    - my-repo-server
  FilterRegexp: latest
  TargetRegexp: "^[0-9a-f]{5,40}$"
  Phases: |
    - name: staging
      autoDeploy: true
      notifyChannel: "#dev-notifications"
      destination:
        kind: ecs
        ecs:
          taskDefinitionArn: arn:aws:ecs:ap-northeast-1:xxxx:task-definition/my-repo-staging
          image: xxxx.dkr.ecr.ap-northeast-1.amazonaws.com/my-repo
```
